development:
  adapter: postgresql
  database: ant
  username: ant
  password: suka
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000


production:
  adapter: postgresql
  database: ant
  username: ant
  password: suka
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
